#!/usr/bin/env python
# Add auto-completion and a stored history file of commands to your Python
# interactive interpreter. Requires Python 2.0+, readline. Autocomplete is
# bound to the Esc key by default (you can change it - see readline docs).
#
# Store the file in ~/.pystartup, and set an environment variable to point
# to it, e.g. "export PYTHONSTARTUP=/max/home/itamar/.pystartup" in bash.
#
# Note that PYTHONSTARTUP does *not* expand "~", so you have to put in the
# full path to your home directory.

import rlcompleter
import readline
readline.parse_and_bind("tab: complete")

import os
histfile = os.path.join(os.environ["HOME"], ".pyhist")
try:
    readline.read_history_file(histfile)
except IOError:
    pass

import atexit
atexit.register(readline.write_history_file, histfile)

del os, histfile, atexit


## def autoload_exc(type, value, traceback):
##     modulename = value.args[0].split()[1][1:-1]
##     f_locals = traceback.tb_frame.f_locals
##     f_globals = traceback.tb_frame.f_globals
##     exec "import %s" % modulename in f_locals, f_globals
##     exec traceback.tb_frame.f_code in f_locals, f_globals
 
## import sys
## sys.excepthook = autoload_exc
## del sys, autoload_exc
